name: Tests and Linter

on:
  push:
    branches: [ dev, master]
  pull_request:
    branches: [ master ]
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: npm install, lint and test
        run: |
          npm install
          npm run lint
          npm test
